image: ilyasemenov/gitlab-ci-git-push

stages:
  - prepare
  - integrate
  - deploy

# ---------------------------------------------------------------------------------------------- #
# -------------------------------------- VARIABLES --------------------------------------------- #
# ---------------------------------------------------------------------------------------------- # v

variables:
   COMPOSE_PROJECT_NAME: $CI_PROJECT_NAME-$CI_BUILD_REF_NAME
   VIRTUAL_HOST: $CI_PROJECT_NAME.staging.motius.de
# ---------------------------------------------------------------------------------------------- #
# ---------------------------------------- CLEAN ----------------------------------------------- #  down --remove-orphans -v
# ---------------------------------------------------------------------------------------------- #
prepare:clean:
   stage: prepare
   script:
       - docker-compose rm -f
   allow_failure: true
   only:
       - master
   tags:
       - staging

# ---------------------------------------------------------------------------------------------- #
# --------------------------------------- INTEGRATE -------------------------------------------- #
# ---------------------------------------------------------------------------------------------- #
integrate:build:
   stage: integrate
   script:
       - docker-compose build
   tags:
       - staging

# ---------------------------------------------------------------------------------------------- #
# ----------------------------------------- DEPLOY --------------------------------------------- #
# ---------------------------------------------------------------------------------------------- #

deploy:general:
    stage: deploy
    script:
        - docker-compose up -d
    only:
        - master
    tags:
        - staging

deploy:push-github:
    stage: deploy
    only:
        - master
    script: git-push git@github.com:motius/slack-onboarding-bot.git
    tags:
        - staging-docker

# ---------------------------------------------------------------------------------------------- #
# ----------------------------------------- LOGS --------------------------------------------- #
# ---------------------------------------------------------------------------------------------- #

logs:
    stage: deploy
    script:
        - docker-compose logs
    when: manual
    tags:
        - staging
 
# ---------------------------------------------------------------------------------------------- #
# ----------------------------------------- EXPORT --------------------------------------------- #
# ---------------------------------------------------------------------------------------------- #

export:
    stage: deploy
    script:
        - docker-compose exec -T db mongoexport --db test --collection tickets > tickets.json
        - docker-compose exec -T db mongoexport --db test --collection admins > admins.json
        - docker-compose exec -T db mongoexport --db test --collection responses > responses.json
        - docker-compose exec -T db mongoexport --db test --collection users > users.json
    artifacts:
        paths:
            - tickets.json
            - admins.json
            - responses.json
            - users.json
    when: manual
    tags:
        - staging
 