version: '2'

services:
  db:
    image: "mongo:latest"
    networks:
      - proxy
    expose: 
      - 27017
      
  bot:
    environment:
      MONGODB_URI: mongodb://db:27017
      SLACK_TOKEN: ${SLACK_TOKEN}
      WIT_TOKEN: ${WIT_TOKEN}
    build: .
    links:
      - db:mongo
    depends_on:
      - db
    networks:
      - proxy

networks:
  proxy:
    external:
      name: motius_proxy
