version: '2'

services:
  db:
    image: "mongo:latest"
    environment: 
      NetworkName: motius_proxy
      VIRTUAL_HOST: "mongo.${VIRTUAL_HOST}"
      VIRTUAL_PORT: 27017
      CERT_NAME: ""
    networks:
      - proxy
    expose: 
      - 27017
      
  bot:
    build: .
    links:
      - db:mongo
    depends_on:
      - db
    networks:
      - proxy

networks:
  proxy:
    external:
      name: motius_proxy
